/**:
  ros__parameters:
    filter1:
      name: arm
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        min_x: -0.45
        max_x: -0.10
        min_y: -0.10
        max_y: 0.10
        min_z: -0.20
        max_z: 0.80
        invert: false